/**
 * Stage 8B — Markdown renderer. Walks the canonical ReportModel; no report
 * content decisions are made here.
 */
import type { ReportBlock, ReportModel } from '../types';

function block(b: ReportBlock): string {
  switch (b.kind) {
    case 'paragraph':
      return b.label ? `**${b.label}:** ${b.text}\n` : `${b.text}\n`;
    case 'keyValue':
      return b.pairs.map((p) => `- **${p.label}:** ${p.value}`).join('\n') + '\n';
    case 'scoreTable':
      return (
        `| ${b.columns[0]} | ${b.columns[1]} |\n| --- | --- |\n` +
        b.rows.map((r) => `| ${r.label} | ${r.value} |`).join('\n') +
        '\n'
      );
    case 'list':
      return b.items
        .map((it, i) => (b.ordered ? `${i + 1}. ${it}` : `- ${it}`))
        .join('\n') + '\n';
    case 'callout':
      return `> ${b.title ? `**${b.title}** — ` : ''}${b.text}\n`;
  }
}

export function renderMarkdown(model: ReportModel): string {
  const out: string[] = [];
  out.push(`# ${model.brand.name} — ${model.brand.tagline}`);
  out.push(`## ${model.title}`);
  if (model.demoBadge) out.push(`> 🧪 **Demonstration Mode**`);
  out.push('');
  out.push(model.headerFields.map((f) => `- **${f.label}:** ${f.value}`).join('\n'));
  out.push('');
  out.push(`**Overall Score:** ${model.overall.score.toFixed(1)} / ${model.overall.max}`);
  if (model.overall.verdict) out.push(`\n${model.overall.verdict}`);
  out.push('');

  for (const section of model.sections) {
    out.push(`## ${section.heading}`);
    out.push('');
    for (const b of section.blocks) out.push(block(b));
    out.push('');
  }

  out.push('---');
  out.push(`### ${model.transparency.title}`);
  out.push('');
  out.push(model.transparency.body);
  if (model.transparency.provenance.length) {
    out.push('');
    out.push(
      model.transparency.provenance.map((p) => `- **${p.label}:** ${p.value}`).join('\n')
    );
  }
  out.push('');
  out.push(`*Generated by ${model.brand.name}.*`);
  return out.join('\n');
}
