/**
 * Stage 8B — Rich Text Format (.rtf) renderer. Produces a portable RTF 1.x
 * document that opens in Word, Pages, WordPad, TextEdit, etc. Walks the
 * canonical ReportModel.
 */
import type { ReportBlock, ReportModel } from '../types';

// Brand red in RTF colour table (index 1). Index 0 = auto/black, 2 = muted grey.
const COLOR_TABLE = `{\\colortbl;\\red213\\green33\\blue34;\\red71\\green85\\blue105;}`;

/** Escape text for the RTF body: control chars, braces, and non-ASCII → \uN. */
function esc(s: string): string {
  let out = '';
  for (const ch of String(s)) {
    const code = ch.codePointAt(0)!;
    if (ch === '\\') out += '\\\\';
    else if (ch === '{') out += '\\{';
    else if (ch === '}') out += '\\}';
    else if (ch === '\n') out += '\\line ';
    else if (code > 127) out += `\\u${code}?`;
    else out += ch;
  }
  return out;
}

const NL = '\\par\n';

function para(text: string, opts: { bold?: boolean; color?: number; size?: number } = {}): string {
  let s = '';
  if (opts.color) s += `\\cf${opts.color} `;
  if (opts.size) s += `\\fs${opts.size} `;
  if (opts.bold) s += '\\b ';
  s += esc(text);
  if (opts.bold) s += '\\b0 ';
  if (opts.size) s += '\\fs22 ';
  if (opts.color) s += '\\cf0 ';
  return s + NL;
}

function block(b: ReportBlock): string {
  switch (b.kind) {
    case 'paragraph':
      return (b.label ? `\\b ${esc(b.label)}:\\b0  ` : '') + esc(b.text) + NL;
    case 'keyValue':
      return b.pairs.map((p) => `\\b ${esc(p.label)}:\\b0  ${esc(p.value)}${NL}`).join('');
    case 'scoreTable':
      return b.rows.map((r) => `\\b ${esc(r.label)}\\b0 \\tab ${esc(r.value)}${NL}`).join('');
    case 'list':
      return b.items
        .map((it, i) => `${b.ordered ? `${i + 1}.` : '\\bullet'} ${esc(it)}${NL}`)
        .join('');
    case 'callout':
      return (b.title ? `\\b ${esc(b.title)}\\b0  ` : '') + esc(b.text) + NL;
  }
}

export function renderRtf(model: ReportModel): string {
  let body = '';
  body += para(`${model.brand.name.toUpperCase()} — ${model.brand.tagline}`, { bold: true, color: 1, size: 34 });
  body += para(model.title, { bold: true, color: 2, size: 24 });
  if (model.demoBadge) body += para('[ DEMONSTRATION MODE ]', { bold: true, color: 1 });
  body += NL;

  for (const f of model.headerFields) body += `\\b ${esc(f.label)}:\\b0  ${esc(f.value)}${NL}`;
  body += NL;
  body += para(`Overall Score: ${model.overall.score.toFixed(1)} / ${model.overall.max}`, { bold: true, color: 1, size: 26 });
  if (model.overall.verdict) body += esc(model.overall.verdict) + NL;
  body += NL;

  for (const section of model.sections) {
    body += para(section.heading, { bold: true, color: 1, size: 24 });
    for (const b of section.blocks) body += block(b);
    body += NL;
  }

  body += para(model.transparency.title, { bold: true, color: 1, size: 22 });
  body += esc(model.transparency.body) + NL;
  for (const p of model.transparency.provenance) body += `\\b ${esc(p.label)}:\\b0  ${esc(p.value)}${NL}`;
  body += NL;
  body += para(`Generated by ${model.brand.name}.`, { color: 2 });

  return `{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Helvetica;}}${COLOR_TABLE}\\fs22\n${body}}`;
}
