/**
 * Stage 8B — Plain-text renderer. Walks the canonical ReportModel.
 */
import type { ReportBlock, ReportModel } from '../types';

function rule(char = '─', width = 64): string {
  return char.repeat(width);
}

function heading(text: string): string {
  return `${text.toUpperCase()}\n${rule('-', text.length)}`;
}

function block(b: ReportBlock): string {
  switch (b.kind) {
    case 'paragraph':
      return b.label ? `${b.label}: ${b.text}` : b.text;
    case 'keyValue':
      return b.pairs.map((p) => `  ${p.label}: ${p.value}`).join('\n');
    case 'scoreTable':
      return b.rows.map((r) => `  ${r.label.padEnd(24)} ${r.value}`).join('\n');
    case 'list':
      return b.items
        .map((it, i) => (b.ordered ? `  ${i + 1}. ${it}` : `  • ${it}`))
        .join('\n');
    case 'callout':
      return `${b.title ? `[${b.title}] ` : ''}${b.text}`;
  }
}

export function renderText(model: ReportModel): string {
  const out: string[] = [];
  out.push(rule('='));
  out.push(`${model.brand.name.toUpperCase()} — ${model.brand.tagline}`);
  out.push(model.title);
  if (model.demoBadge) out.push('[ DEMONSTRATION MODE ]');
  out.push(rule('='));
  out.push('');
  for (const f of model.headerFields) out.push(`  ${f.label}: ${f.value}`);
  out.push('');
  out.push(`OVERALL SCORE: ${model.overall.score.toFixed(1)} / ${model.overall.max}`);
  if (model.overall.verdict) {
    out.push('');
    out.push(model.overall.verdict);
  }
  out.push('');

  for (const section of model.sections) {
    out.push('');
    out.push(heading(section.heading));
    for (const b of section.blocks) out.push(block(b));
  }

  out.push('');
  out.push(rule('='));
  out.push(model.transparency.title.toUpperCase());
  out.push(rule('='));
  out.push(model.transparency.body);
  for (const p of model.transparency.provenance) out.push(`  ${p.label}: ${p.value}`);
  out.push('');
  out.push(`Generated by ${model.brand.name}.`);
  return out.join('\n');
}
